### ISSUE TITLE
[ERROR] Couldn't pass ProxyInitializeEvent to limbofilter

### ISSUE THREAD

**Issue by WieszczY85** [Elytrium/LimboFilter#14]
**Describe the bug**
Error in console

`[16:32:32] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.protocol.packet.chat.SystemChat.<init>(net.kyori.adventure.text.Component, int)'
	at net.elytrium.limbofilter.cache.CachedPackets.createChatPacket(CachedPackets.java:122) ~[?:?]
	at net.elytrium.limbofilter.cache.CachedPackets.createPackets(CachedPackets.java:74) ~[?:?]
	at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:164) ~[?:?]
	at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:124) ~[?:?]
	at net.elytrium.limbofilter.Lmbda$9.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.1.2-SNAPSHOT (git-fee292bc-b169)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.1.2-SNAPSHOT (git-fee292bc-b169)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.1.2-SNAPSHOT (git-fee292bc-b169)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - limboapi-plugin-1.0.5-jdk17, downloaded from https://www.spigotmc.org/resources/limboapi.95748/
 - limbofilter-1.0.5-jdk17, downloaded from https://www.spigotmc.org/resources/limbofilter.99412/

 - /velocity dump link [](https://dump.velocitypowered.com/aqurukifuk.json)

**Comment by hevav** [comment]
Update to 1.0.6-snapshot

**Comment by WieszczY85** [comment]
Where can I find him?

**Comment by hevav** [comment]
https://github.com/Elytrium/LimboFilter/releases
https://github.com/Elytrium/LimboAPI/releases
