### ISSUE TITLE
LIMBOFILTER BUG[BUG] 

### ISSUE THREAD

**Issue by VXNAMAN** [Elytrium/LimboFilter#16]
[17:19:32 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.protocol.packet.chat.SystemChat.<init>(net.kyori.adventure.text.Component, int)'
        at net.elytrium.limbofilter.cache.CachedPackets.createChatPacket(CachedPackets.java:122) ~[?:?]
        at net.elytrium.limbofilter.cache.CachedPackets.createPackets(CachedPackets.java:74) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:164) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:124) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[bungeecord.jar:3.1.2-SNAPSHOT (git-048fd903-b174)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[bungeecord.jar:3.1.2-SNAPSHOT (git-048fd903-b174)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[bungeecord.jar:3.1.2-SNAPSHOT (git-048fd903-b174)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by mdxd44** [comment]
Use latest dev builds.

**Comment by VXNAMAN** [comment]
Its up-to-date, this is the up-to-date version right: limbofilter-1.0.5-jdk17.jar

**Comment by KurumiFake** [comment]
> Its up-to-date, this is the up-to-date version right: limbofilter-1.0.5-jdk17.jar

no, see https://github.com/Elytrium/LimboFilter/releases

**Comment by AVuTuVA** [comment]
![image](https://user-images.githubusercontent.com/66278054/185623405-2c834a5c-54f5-4766-9e2f-00b6729abe0a.png)
