### ISSUE TITLE
[BUG] Couldn't pass ProxyInitializeEvent to limbofilter

### ISSUE THREAD

**Issue by NEIZ21** [Elytrium/LimboFilter#18]
I use the latest dev builds of LimboAPI,LimbAuth,LimboFilter plugins = 1.0.6
The LimboFilter plugin does not work, and LimboAuth just has a black screen instead of the background (overworld) But it shows the registration

The error is written below

Errore:
[10:47:53] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.InternalError: java.lang.reflect.InvocationTargetException
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86) ~[?:?]
at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74) ~[?:?]
at java.awt.Font.getFont2D(Font.java:524) ~[?:?]
at java.awt.Font$FontAccessImpl.getFont2D(Font.java:264) ~[?:?]
at sun.font.FontUtilities.getFont2D(FontUtilities.java:147) ~[?:?]
at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1109) ~[?:?]
at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1098) ~[?:?]
at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:163) ~[?:?]
at java.awt.Font.createGlyphVector(Font.java:2740) ~[?:?]
at net.elytrium.limbofilter.captcha.painter.RenderedFont.<init>(RenderedFont.java:43) ~[?:?]
at net.elytrium.limbofilter.captcha.CaptchaGenerator.getRenderedFont(CaptchaGenerator.java:127) ~[?:?]
at net.elytrium.limbofilter.captcha.CaptchaGenerator.initializeGenerator(CaptchaGenerator.java:96) ~[?:?]
at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:187) ~[?:?]
at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:135) ~[?:?]
at net.elytrium.limbofilter.Lmbda$4.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-cae41c33-b177)]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84) ~[?:?]
... 21 more
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1260) ~[?:?]
at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:223) ~[?:?]
at sun.awt.FontConfiguration.init(FontConfiguration.java:106) ~[?:?]
at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:711) ~[?:?]
at sun.font.SunFontManager$2.run(SunFontManager.java:352) ~[?:?]
at sun.font.SunFontManager$2.run(SunFontManager.java:309) ~[?:?]
at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
at sun.font.SunFontManager.<init>(SunFontManager.java:309) ~[?:?]
at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[?:?]
at sun.awt.X11FontManager.<init>(X11FontManager.java:56) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84) ~[?:?]
... 21 more

I use translate.yandex.ru :)

**Comment by JNNGL** [comment]
install font-config

**Comment by NEIZ21** [comment]
???

**Comment by AVuTuVA** [comment]
sudo apt install fontconfig

**Comment by NEIZ21** [comment]
ok

**Comment by NEIZ21** [comment]
> sudo apt install fontconfig

Thanks! It helped a lot!

**Comment by stupenki** [comment]
> sudo apt устанавливает fontconfig
what should I do with this command? where should I put it?
