### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gangmaster-dev** [Elytrium/LimboFilter#20]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. download the latest velocity
2. put in, start the velocity
3. and you will see the error

**Expected behavior**
when i start the server, a big error message pops up.

**Screenshots**
![image](https://user-images.githubusercontent.com/56204919/187472719-37636126-00ac-494b-8546-6d33fb8bc1f1.png)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.0.5 (downloaded from github releases)
 - LimboFilter 1.0.5 (downloaded from github releases)

 - /velocity dump link [https://dump.velocitypowered.com/awaderugid.json]

**Additional context**
[17:04:04 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.protocol.packet.chat.SystemChat.<init>(net.kyori.adventure.text.Component, int)'
        at net.elytrium.limbofilter.cache.CachedPackets.createChatPacket(CachedPackets.java:122) ~[?:?]
        at net.elytrium.limbofilter.cache.CachedPackets.createPackets(CachedPackets.java:74) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:164) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:124) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-6547ccaa-b179)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by hevav** [comment]
Update LimboFilter
