### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 2006lev-Web** [Elytrium/LimboFilter#23]
An error occurs when starting the server
```

[14:06:43 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
[14:06:43 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
[14:06:43 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
[14:06:43 ERROR]:       at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:148)
[14:06:43 ERROR]:       at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
[14:06:43 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:176)
[14:06:43 ERROR]:       at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:163)
[14:06:43 ERROR]:       at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
[14:06:43 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:126)
[14:06:43 ERROR]:       at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
[14:06:43 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:87)
[14:06:43 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:69)
[14:06:43 ERROR]:       at com.google.inject.Guice.createInjector(Guice.java:59)
[14:06:43 ERROR]:       at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:119)
[14:06:43 ERROR]:       at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:151)
[14:06:43 ERROR]:       at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343)
[14:06:43 ERROR]:       at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224)
[14:06:43 ERROR]:       at com.velocitypowered.proxy.Velocity.main(Velocity.java:64)
[14:06:43 ERROR]: Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lnet/elytrium/limboapi/api/protocol/packets/PacketFactory;
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
[14:06:43 ERROR]:       at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
[14:06:43 ERROR]:       at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:69)
[14:06:43 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75)
[14:06:43 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
[14:06:43 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
[14:06:43 ERROR]:       at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
[14:06:43 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[14:06:43 ERROR]:       ... 21 more
[14:06:43 ERROR]: Caused by: java.lang.NoClassDefFoundError: Lnet/elytrium/limboapi/api/protocol/packets/PacketFactory;
[14:06:43 ERROR]:       at java.base/java.lang.Class.getDeclaredFields0(Native Method)
[14:06:43 ERROR]:       at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
[14:06:43 ERROR]:       at java.base/java.lang.Class.getDeclaredFields(Class.java:2248)
[14:06:43 ERROR]:       at com.google.inject.internal.DeclaredMembers.getDeclaredFields(DeclaredMembers.java:40)
[14:06:43 ERROR]:       at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:800)
[14:06:43 ERROR]:       at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:710)
[14:06:43 ERROR]:       at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:423)
[14:06:43 ERROR]:       at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:92)
[14:06:43 ERROR]:       at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:40)
[14:06:43 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:49)
[14:06:43 ERROR]:       at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
[14:06:43 ERROR]:       at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
[14:06:43 ERROR]:       at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
[14:06:43 ERROR]:       ... 36 more
[14:06:43 ERROR]: Caused by: java.lang.ClassNotFoundException: net.elytrium.limboapi.api.protocol.packets.PacketFactory
[14:06:43 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:84)
[14:06:43 ERROR]:       at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61)
[14:06:43 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[14:06:43 ERROR]:       ... 52 more


**Additional context**
Add any other context about the problem here.

```

**Comment by SkyWatcher2019** [comment]
Update plugins

**Comment by 2006lev-Web** [comment]
> Обновление плагинов

The plugin has just been updated and this error

**Comment by 2006lev-Web** [comment]
Even after that, the server stopped working

**Comment by JNNGL** [comment]
have you installed [limboapi](https://github.com/Elytrium/LimboAPI)?

**Comment by 2006lev-Web** [comment]
All I updated limboapi I didn't know that it also needed to be updated
