### ISSUE TITLE
[BUG] limbofilter plugin error

### ISSUE THREAD

**Issue by SnonSS** [Elytrium/LimboFilter#24]
Updated the kernel to the latest version and plugins: limboapi-plugin-1.0.6-jdk17, LimboAuth.Social.Addon-1.0.2-jdk17, limboauth-1.0.6-jdk17, But the limbofilter-1.0.5-jdk17 plugin does not want to work what could be the problem?

Here is another error when turning on the server:

[17:44:31 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.NoSuchMethodError: 'void com.velocitypowered.proxy.protocol.packet.chat.SystemChat.<init>(net.kyori.adventure.text.Component, int)'
        at net.elytrium.limbofilter.cache.CachedPackets.createChatPacket(CachedPackets.java:122) ~[?:?]
        at net.elytrium.limbofilter.cache.CachedPackets.createPackets(CachedPackets.java:74) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:164) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:124) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-f6b032cb-b182)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-f6b032cb-b182)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-f6b032cb-b182)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by JNNGL** [comment]
update limbofilter

**Comment by SnonSS** [comment]
> обновление лимбофильтра

Plugin latest version

**Comment by SnonSS** [comment]
And there is such a thank you
