### ISSUE TITLE
Ошибка на Ubuntu 20.04.3

### ISSUE THREAD

**Issue by maximen39** [Elytrium/LimboFilter#3]
На Ubuntu 20.04.3 (Linux 5.4.0-94-generic x86_64) если нет пакета шрифтов, то возникает ошибка.
Решается установкой пакета ttf-dejavu: `sudo apt-get install ttf-dejavu`
Предлагаю добавить в документацию, т.к для некоторых пользователей это может быть не очевидно
```
[10:29:15 ERROR]: Exception in thread "pool-8-thread-1" java.lang.Error: Probable fatal error: No physical fonts found.
[10:29:15 ERROR]:       at java.desktop/sun.font.SunFontManager.lambda$getDefaultPhysicalFont$0(SunFontManager.java:1056)
[10:29:15 ERROR]:       at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[10:29:15 ERROR]:       at java.desktop/sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1056)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:291)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeFont.getMapper(CompositeFont.java:433)
[10:29:15 ERROR]:       at java.desktop/sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1105)
[10:29:15 ERROR]:       at java.desktop/sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:163)
[10:29:15 ERROR]:       at java.desktop/java.awt.Font.createGlyphVector(Font.java:2747)
[10:29:15 ERROR]:       at net.elytrium.limbofilter.captcha.painter.CaptchaPainter.draw(CaptchaPainter.java:68)
[10:29:15 ERROR]:       at net.elytrium.limbofilter.captcha.painter.CaptchaPainter.draw(CaptchaPainter.java:57)
[10:29:15 ERROR]:       at net.elytrium.limbofilter.captcha.CaptchaGenerator.genNewPacket(CaptchaGenerator.java:134)
[10:29:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:29:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:29:15 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[10:29:15 ERROR]: Exception in thread "pool-8-thread-2" java.lang.Error: Probable fatal error: No physical fonts found.
[10:29:15 ERROR]:       at java.desktop/sun.font.SunFontManager.lambda$getDefaultPhysicalFont$0(SunFontManager.java:1056)
[10:29:15 ERROR]:       at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[10:29:15 ERROR]:       at java.desktop/sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1056)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:291)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeFont.getSlotFont(CompositeFont.java:376)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62)
[10:29:15 ERROR]:       at java.desktop/sun.font.CompositeFont.getMapper(CompositeFont.java:433)
[10:29:15 ERROR]:       at java.desktop/sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1105)
[10:29:15 ERROR]:       at java.desktop/sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:163)
[10:29:15 ERROR]:       at java.desktop/java.awt.Font.createGlyphVector(Font.java:2747)
[10:29:15 ERROR]:       at net.elytrium.limbofilter.captcha.painter.CaptchaPainter.draw(CaptchaPainter.java:68)
[10:29:15 ERROR]:       at net.elytrium.limbofilter.captcha.painter.CaptchaPainter.draw(CaptchaPainter.java:57)
[10:29:15 ERROR]:       at net.elytrium.limbofilter.captcha.CaptchaGenerator.genNewPacket(CaptchaGenerator.java:134)
[10:29:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:29:15 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:29:15 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hevav** [comment]
Все же, это не ошибка плагина, а ошибка вашей системы. И все же, обычно ошибка появляется только на самых дешевых хостингах.
А фиксится это установкой совсем другого пакета - ``fontconfig``. Да, он есть в зависимостях у ``ttf-dejavu``, но устанавливать лишнего точно не нужно.
Но хорошо, я укажу это в будущем.

**Comment by maximen39** [comment]
Не думаю что aws это дешевый хостинг)

**Comment by hevav** [comment]
Допустим что это единичный случай. Тем более насколько я помню, в AWS есть различные виды образов, и с минимальной установкой, и с обычной.
В G-Core Cloud, Yandex.Cloud, VK CS, OVHcloud, Scaleway нужный пакет fontconfig предустановлен.
