### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AdhityaXD1604** [Elytrium/LimboFilter#34]
[12:12:34 WARN]: Could not load plugin from file plugins/limbofilter-1.0.6-jdk17.jar
java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:434) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:276) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
[12:12:34 WARN]: Could not load plugin from file plugins/limboapi-plugin-1.0.6-jdk17.jar
java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:434) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:276) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:c7caa4b:506]

**Comment by licen150** [comment]
This plugin working ONLY on velocity proxy

**Comment by SkyWatcher2019** [comment]
Limbo plugins works **only** on [Velocity](https://docs.papermc.io/velocity)

**Comment by JNNGL** [comment]
^
