### ISSUE TITLE
[BUG] Couldn't pass ProxyInitializeEvent to limbofilter

### ISSUE THREAD

**Issue by 8Riven8** [Elytrium/LimboFilter#54]
When I start the proxy, this error appears in the console:

[23:51:54 INFO]: Loading plugins...
[23:51:54 INFO] [limboapi]: Initializing Simple Virtual World system...
[23:51:55 INFO] [limboapi]: Hooking into EventManager, PlayerList/UpsertPlayerInfo and StateRegistry...
[23:51:55 INFO]: Loaded plugin limboapi 1.1.12 by Elytrium (https://elytrium.net/)
[23:51:55 INFO]: Loaded plugin limbofilter 1.1.10 by Elytrium (https://elytrium.net/)
[23:51:55 INFO]: Loaded plugin tcpshield 2.6.1 by TCPShield
[23:51:55 INFO]: Loaded 3 plugins
[23:51:55 INFO] [limboapi]: Creating and preparing packets...
[23:51:55 INFO] [limboapi]: Loaded!
[23:51:56 INFO] [limbofilter]: Current captcha generator settings will consume 0.08GB RAM normally and 0.15GB RAM on reloads
[23:51:56 INFO] [limbofilter]: Modify the config to decrease RAM consumption
[23:51:57 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.ExceptionInInitializerError: null
        at net.elytrium.limboapi.LimboAPI.createLimbo(LimboAPI.java:370) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:305) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:174) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.server.LimboImpl.<clinit>(LimboImpl.java:832) ~[?:?]
        ... 10 more
Caused by: java.lang.NoSuchFieldException: no such field: com.velocitypowered.proxy.protocol.packet.JoinGame.currentDimensionData/net.kyori.adventure.nbt.CompoundBinaryTag/putField
        at java.lang.invoke.MemberName.makeAccessException(MemberName.java:978) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:3043) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.<clinit>(LimboImpl.java:813) ~[?:?]
        ... 10 more
Caused by: java.lang.NoSuchFieldError: currentDimensionData
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085) ~[?:?]
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3641) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.findSetter(MethodHandles.java:3043) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.<clinit>(LimboImpl.java:813) ~[?:?]
        ... 10 more

Screenshot:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/104576430/228666602-5d54f417-3578-45d3-b4fb-150ade0ef161.png">

**Comment by 8Riven8** [comment]
@hevav Thanks! It's working!
