### ISSUE TITLE
[BUG] Velocity 3.2.0, Java 17

### ISSUE THREAD

**Issue by astrofox09** [Elytrium/LimboFilter#63]
**Describe the bug**
Cannot start LimboFilter

**To Reproduce**
1. just run latest release of LimboFilter on Velocity 3.2.0

**Expected behavior**
Plugin will start

**Screenshots**
```
[11:56:30 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.UnsupportedOperationException: null
at net.elytrium.limboapi.LimboAPI.registerPacket(LimboAPI.java:439) ~[?:?]		

at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:140) ~[?:?]at net.elytrium.limbofilter.Lmbda$4.execute(Unknown Source) ~[?:?]		
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]at java.lang.Thread.run(Thread.java:833) [?:?]	
```

**Server Info (please complete the following information):**
 - Velocity 3.2.0-SNAPSHOT
 - LimboAPI 1.1.16
 - LimboFilter 1.1.10

**Comment by JNNGL** [comment]
Update LimboFilter.
