### ISSUE TITLE
[BUG] Font troubles

### ISSUE THREAD

**Issue by astrofox09** [Elytrium/LimboFilter#64]
**Describe the bug**
Font troubles on plugin loading

**Screenshots**
```
	[16:47:39 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:87) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:75) ~[?:?]
	at java.awt.Font.getFont2D(Font.java:526) ~[?:?]
	at java.awt.Font$FontAccessImpl.getFont2D(Font.java:265) ~[?:?]
	at sun.font.FontUtilities.getFont2D(FontUtilities.java:148) ~[?:?]
	at sun.font.StandardGlyphVector.initFontData(StandardGlyphVector.java:1109) ~[?:?]
	at sun.font.StandardGlyphVector.init(StandardGlyphVector.java:1098) ~[?:?]
	at sun.font.StandardGlyphVector.<init>(StandardGlyphVector.java:163) ~[?:?]
	at java.awt.Font.createGlyphVector(Font.java:2747) ~[?:?]
	at net.elytrium.limbofilter.captcha.painter.RenderedFont.<init>(RenderedFont.java:43) ~[?:?]
	at net.elytrium.limbofilter.captcha.CaptchaGenerator.getRenderedFont(CaptchaGenerator.java:216) ~[?:?]
	at net.elytrium.limbofilter.captcha.CaptchaGenerator.initializeGenerator(CaptchaGenerator.java:133) ~[?:?]
	at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:217) ~[?:?]
	at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:140) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	

	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:85) ~[?:?]		... 21 more
Caused by: java.lang.NullPointerException: Cannot load from short array because "sun.awt.FontConfiguration.head" is null
	at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[?:?]
	at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224) ~[?:?]
at sun.font.SunFontManager$2.run(SunFontManager.java:315) ~[?:?]at sun.awt.FontConfiguration.init(FontConfiguration.java:106) ~[?:?]
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706) ~[?:?]
	at sun.font.SunFontManager$2.run(SunFontManager.java:358) ~[?:?]
		
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at sun.font.SunFontManager.<init>(SunFontManager.java:315) ~[?:?]

at sun.awt.FcFontManager.<init>(FcFontManager.java:35) ~[?:?]
	at sun.awt.X11FontManager.<init>(X11FontManager.java:56) ~[?:?]		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	

	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]at sun.font.FontManagerFactory$1.run(Fo	
ntManagerFactory.java:85) ~[?:?]... 21 more	

```

**Server Info (please complete the following information):**
- Velocity 3.2.0-SNAPSHOT
- LimboFilter 1.1.11
- LimboAPI 1.1.16

**Comment by JNNGL** [comment]
sudo apt install FontConfiguration

**Comment by astrofox09** [comment]
thanks!
