### ISSUE TITLE
[BUG] Spam console Captcha

### ISSUE THREAD

**Issue by TAZIKLIK** [Elytrium/LimboFilter#66]
Все самое новое, плагины и сам велосити.
Спамит в консоль:
[11:41:36 ERROR]: Exception in thread "CaptchaGeneratorThread" java.lang.NullPointerException: Cannot invoke "net.elytrium.limbofilter.captcha.CaptchaHolder.setNext(net.elytrium.limbofilter.captcha.CaptchaHolder)" because "this.lastHolder" is null [11:41:36 ERROR]: at net.elytrium.limbofilter.cache.captcha.CachedCaptcha.build(CachedCaptcha.java:112) [11:41:36 ERROR]: at net.elytrium.limbofilter.captcha.CaptchaGenerator.lambda$generateImages$7(CaptchaGenerator.java:296) [11:41:36 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [11:41:36 ERROR]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [11:41:36 ERROR]: at java.base/java.lang.Thread.run(Thread.java:831)

Конфиг:
[config.txt](https://github.com/Elytrium/LimboFilter/files/12170893/config.txt)

**Comment by TAZIKLIK** [comment]
Нашёл решение, в limbo api стояли версии обе latest. Незнаю почему не схавал. У меня просто сервер на 1.20.1

**Comment by mdxd44** [comment]
latest работает только для prepare-max-version.
