### ISSUE TITLE
[BUG] Couldn't pass ProxyInitializeEvent to limboapi

### ISSUE THREAD

**Issue by tyryndyc** [Elytrium/LimboFilter#67]
hi, i  have encountered an error Couldn't pass ProxyInitializeEvent to limboapi. i use limboapi-1.1.2 and limbofilter-1.1.1-jdk17 versions

[22:39:15 ERROR]: Couldn't pass ProxyInitializeEvent to limboapi
java.lang.ClassCastException: class com.velocitypowered.proxy.event.VelocityEventManager cannot be cast to class net.elytrium.limboapi.injection.event.EventManagerHook (com.velocitypowered.proxy.event.VelocityEventManager is in unnamed module of loader 'app'; net.elytrium.limboapi.injection.event.EventManagerHook is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @2d2acd89)
        at net.elytrium.limboapi.LimboAPI.postProxyInitialization(LimboAPI.java:244) ~[?:?]
        at net.elytrium.limboapi.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

and screenshot 

![image](https://github.com/Elytrium/LimboFilter/assets/140925251/91becda6-b6ea-4a4f-8319-3ba427f23a8c)

im trying fix it several days please help!
thank in advance

**Comment by mdxd44** [comment]
Update LimboAPI.

**Comment by tyryndyc** [comment]
> Update LimboAPI.

i update limboapi on 1.1.16 version and it still not working((((

**Comment by mdxd44** [comment]
Also update velocity and limbofilter.
