### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ponnnwedw** [Elytrium/LimboFilter#68]
**Describe the bug**
The bug started happening when I put limboapi and limpofilter on Velocity

**Screenshots**
Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.IllegalArgumentException: can't parse argument number: PRFX
        at java.text.MessageFormat.makeFormat(MessageFormat.java:1454) ~[?:?]
        at java.text.MessageFormat.applyPattern(MessageFormat.java:492) ~[?:?]
        at java.text.MessageFormat.<init>(MessageFormat.java:371) ~[?:?]
        at java.text.MessageFormat.format(MessageFormat.java:860) ~[?:?]
        at net.elytrium.limbofilter.cache.CachedPackets.createCaptchaAttemptsPacket(CachedPackets.java:155) ~[?:?]
        at net.elytrium.limbofilter.cache.CachedPackets.createPackets(CachedPackets.java:68) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:301) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:140) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "PRFX"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at java.text.MessageFormat.makeFormat(MessageFormat.java:1452) ~[?:?]
        ... 14 more

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.1.16, downloaded from https://github.com/Elytrium/LimboAPI/releases?page=1
 - LimboAuth 1.1.12, downloaded from https://github.com/Elytrium/LimboFilter/releases?page=2

 - /velocity dump link https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/265/downloads/velocity-3.2.0-SNAPSHOT-265.jar

**Comment by Ponnnwedw** [comment]
оно само как-то решилось ._.

**Comment by Ponnnwedw** [comment]
оно само как-то решилось ._.
