### ISSUE TITLE
[BUG] An internal error occurred in the server connection.

### ISSUE THREAD

**Issue by ruomeng110** [Elytrium/LimboFilter#72]
[21:41:22] [Netty epoll Worker #15/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] ruomeng110 (/222.214.181.179:42996) has disconnected: 您的连接发生内部错误。
[21:41:22] [Netty epoll Worker #15/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] ruomeng110 (/222.214.181.179:42996): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@62afbc17
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$838/0x0000000801172a98, Packet ID: 2
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:233) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:315) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$838/0x0000000801172a98, Packet ID: 2
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 1, widx: 3, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:38) ~[?:?]
	at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:30) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:145) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:191) ~[?:?]
	at com.viaversion.viaversion.protocols.base.BaseProtocol1_16.passthroughLoginUUID(BaseProtocol1_16.java:29) ~[?:?]
	at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:128) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:366) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:328) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:307) ~[?:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	... 57 more
[21:41:22] [Netty epoll Worker #15/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] ruomeng110 -> Rncraft has disconnected
[21:41:40] [Netty epoll Worker #4/INFO] [com.velocitypowered.proxy.connection.MinecraftConnection]: [server connection] ruomeng110 -> Rncraft has connected
[21:41:40] [Netty epoll Worker #4/WARN] [viaversion]: ERROR IN BaseProtocol1_16 IN REMAP OF 0x02->0x02
[21:41:40] [Netty epoll Worker #4/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] ruomeng110 (/222.214.181.179:43018) has disconnected: 您的连接发生内部错误。
[21:41:40] [Netty epoll Worker #4/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] ruomeng110 (/222.214.181.179:43018): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@7b8a85bc
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$838/0x0000000801172a98, Packet ID: 2
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity-3.2.0-SNAPSHOT-264.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.Abstrac

I can't upload the logs file directly, which is part of the error.

**Comment by kainlighty** [comment]
Yup, fix this, author, please

**Comment by hevav** [comment]
Remove ViaVersion from proxy, ViaVersion is not supported by our plugin

**Comment by kainlighty** [comment]
> Remove ViaVersion from proxy, ViaVersion is not supported by our plugin

Let's say I don't have viaverion, but when checking the server, the list of servers is disabled, and it is impossible to log in, and an error message appears in the console

**Comment by kainlighty** [comment]
Build 265 has no such errors
