### ISSUE TITLE
[BUG] Can't create limbo plugins on new velocity version(#330)

### ISSUE THREAD

**Issue by Tinchik** [Elytrium/LimboFilter#86]
[04:37:09 ERROR]: Can't create plugin limboapi
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: ReflectionException: An unexpected internal error was caught during the reflection operations.
  at LimboAPI.<init>(LimboAPI.java:154)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboAPI
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================
Full classname legend:
======================
LimboAPI:             "net.elytrium.limboapi.LimboAPI"
ReflectionException:  "net.elytrium.commons.utils.reflection.ReflectionException"
VelocityPluginModule: "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
Caused by: net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:192) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$da3d3.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$da3d3.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        … 6 more
Caused by: java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/LegacyPlayerListItem
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:187) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$da3d3.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$da3d3.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        … 6 more
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.LegacyPlayerListItem
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:714) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.<init>(LimboAPI.java:187) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$da3d3.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboapi.LimboAPI$$FastClassByGuice$$da3d3.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        … 6 more
[04:37:09 ERROR]: Can't create plugin limboauth
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboAuth.<init>(LimboAuth.java:184)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboAuth
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================
Full classname legend:
======================
LimboAuth:              "net.elytrium.limboauth.LimboAuth"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.<init>(LimboAuth.java:194) ~[?:?]
        at net.elytrium.limboauth.LimboAuth$$FastClassByGuice$$1d8899.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboauth.LimboAuth$$FastClassByGuice$$1d8899.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        ... 6 more
[04:37:09 ERROR]: Can't create plugin limboauth-social-addon
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at Addon.<init>(Addon.java:128)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating Addon
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================
Full classname legend:
======================
Addon:                  "net.elytrium.limboauth.socialaddon.Addon"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.<init>(Addon.java:135) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon$$FastClassByGuice$$214bdd.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon$$FastClassByGuice$$214bdd.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        ... 6 more
[04:37:09 ERROR]: Can't create plugin limbofilter
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]: NoSuchElementException: No value present
  at LimboFilter.<init>(LimboFilter.java:122)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating LimboFilter
Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
1 error
======================
Full classname legend:
======================
LimboFilter:            "net.elytrium.limbofilter.LimboFilter"
VelocityPluginModule:   "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:126) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:155) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:361) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:243) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:70) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.<init>(LimboFilter.java:131) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter$$FastClassByGuice$$33ad8a.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter$$FastClassByGuice$$33ad8a.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[server.jar:3.3.0-SNAPSHOT (git-0993ce2f-b330)]
        ... 6 more

**Server Info:**
 - All Limbo plugins versions:
 - [LimboAPI 1.1.19]
 - [LimboAuth 1.1.13]
 - [LimboFilter 1.1.14]
 - [LimboAuth social addon 1.0.11]

 - /velocity dump link https://pastebin.com/x5sbgUyS

**Comment by SkyWatcher2019** [comment]
According to your velocity dump, you only have luckperms and skinrestorer installed

**Comment by Tinchik** [comment]
yes

**Comment by Tinchik** [comment]
![image](https://github.com/Elytrium/LimboFilter/assets/78418943/9151b7b2-b375-4f3e-a0a3-97105bc541d3)

**Comment by SkyWatcher2019** [comment]
can you share the full log?

**Comment by Tinchik** [comment]
https://pastebin.com/UKxvZyAv

**Comment by BrainRTP** [comment]
I join the problem. Here's my log:

https://pastebin.com/x4P4T6wK

**Comment by pabloalba16** [comment]
It's because of this: https://github.com/PaperMC/Velocity/commit/2ac8751337befd04f4663575f5d752c748384110

**Comment by BrainRTP** [comment]
And how it fix?
