### ISSUE TITLE
[BUG] Couldn't pass ProxyInitializeEvent

### ISSUE THREAD

**Issue by noImRed** [Elytrium/LimboFilter#91]
[18:51:16 ERROR]: Couldn't pass ProxyInitializeEvent to limbofilter
java.lang.NoSuchFieldError: INSTANCE
        at net.elytrium.limboapi.server.LimboImpl.refresh(LimboImpl.java:228) ~[?:?]
        at net.elytrium.limboapi.server.LimboImpl.<init>(LimboImpl.java:178) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.createLimbo(LimboAPI.java:380) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.reload(LimboFilter.java:261) ~[?:?]
        at net.elytrium.limbofilter.LimboFilter.onProxyInitialization(LimboFilter.java:140) ~[?:?]
        at net.elytrium.limbofilter.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-2ac87513-b329)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.3.0-SNAPSHOT (git-2ac87513-b329)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.3.0-SNAPSHOT (git-2ac87513-b329)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

        
velocity version: velocity 3.3.0 SNAPSHOT 329
limboapi version: 1.1.21
limbofilter version: 1.1.15

**Comment by DHCPCD9** [comment]
Update Velocity to b359 and plugins to dev builds from actions/modrinth.
