### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 44yro4ka** [Elytrium/LimboFilter#92]
**Describe the bug**
My server dont work with your plugins

**To Reproduce**

**Expected behavior**
server start

**Screenshots**
see next point

**Server Info (please complete the following information):**
[10:24:09 ERROR]: Couldn't pass ProxyInitializeEvent to fastmotd
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
        at java.base/java.util.ArrayList.addAll(ArrayList.java:670) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.lambda$sortByProtocolVersion$8(FastMOTD.java:300) ~[?:?]
        at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
        at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.lambda$sortByProtocolVersion$9(FastMOTD.java:300) ~[?:?]
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.sortByProtocolVersion(FastMOTD.java:292) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.generateMOTDGenerators(FastMOTD.java:252) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.reload(FastMOTD.java:212) ~[?:?]
        at net.elytrium.fastmotd.FastMOTD.onProxyInitialization(FastMOTD.java:141) ~[?:?]
        at net.elytrium.fastmotd.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[10:24:10 INFO] [limboapi]: Creating and preparing packets...
[10:24:10 ERROR]: Couldn't pass ProxyInitializeEvent to limboapi
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.protocol.packet.DisconnectPacket com.velocitypowered.proxy.protocol.packet.DisconnectPacket.create(net.kyori.adventure.text.Component, com.velocitypowered.api.network.ProtocolVersion, boolean)'
        at net.elytrium.limboapi.server.CachedPackets.createDisconnectPacket(CachedPackets.java:62) ~[?:?]
        at net.elytrium.limboapi.server.CachedPackets.lambda$createPackets$0(CachedPackets.java:48) ~[?:?]
        at net.elytrium.limboapi.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:133) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:89) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:26) ~[?:?]
        at net.elytrium.limboapi.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:119) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:79) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:26) ~[?:?]
        at net.elytrium.limboapi.server.CachedPackets.createPackets(CachedPackets.java:48) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.reload(LimboAPI.java:281) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.onProxyInitialization(LimboAPI.java:249) ~[?:?]
        at net.elytrium.limboapi.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[10:24:12 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth
net.elytrium.commons.utils.reflection.ReflectionException: An unexpected internal error was caught during the reflection operations.
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:310) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.onProxyInitialization(LimboAuth.java:208) ~[?:?]
        at net.elytrium.limboauth.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:156) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:71) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64) ~[?:?]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:895) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:156) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:71) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166) ~[?:?]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[?:?]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:121) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:839) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:156) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:71) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at java.base/sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
        at java.base/sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593) ~[?:?]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.base/java.net.Socket.connect(Socket.java:633) ~[?:?]
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[?:?]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[?:?]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:121) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:839) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:820) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[?:?]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[?:?]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.fromDriver(DatabaseLibrary.java:156) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.lambda$static$4(DatabaseLibrary.java:71) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connect(DatabaseLibrary.java:115) ~[?:?]
        at net.elytrium.limboauth.dependencies.DatabaseLibrary.connectToORM(DatabaseLibrary.java:131) ~[?:?]
        at net.elytrium.limboauth.LimboAuth.reload(LimboAuth.java:302) ~[?:?]
        ... 8 more
[10:24:13 ERROR]: Couldn't pass ProxyInitializeEvent to limboauth-social-addon
java.lang.IllegalArgumentException: connectionSource argument cannot be null
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.dao.DaoManager.createDao(DaoManager.java:44) ~[?:?]
        at net.elytrium.limboauth.thirdparty.com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:73) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onReload(Addon.java:564) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Addon.onProxyInitialization(Addon.java:148) ~[?:?]
        at net.elytrium.limboauth.socialaddon.Lmbda$5.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[10:24:13 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:20074
[10:24:13 INFO]: Done (8.82s)!
[10:25:38 INFO]: [initial connection] /there is my IP:18870 has disconnected

 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]

**Additional context**
nothing i think

**Comment by UserNugget** [comment]
looks like you are using outdated plugins, and

1) fastmotd was configured improperly
2) you are using outdated limboapi
3) limboauth fails to connect to db
4) limboauth-social-addon fails due to limboauth fails
5) this is not a limbofilter problem

**Comment by 44yro4ka** [comment]
thanks!!!!!
